model_list:
  - model_name: claude-sonnet-4-6
    litellm_params:
      model: anthropic/glm-5.2
      api_base: https://api.z.ai/api/anthropic
      api_key: os.environ/ZAI_API_KEY
      extra_body:
        thinking:
          type: "enabled"
        reasoning_effort: "high"

  - model_name: claude-opus-4-8
    litellm_params:
      model: anthropic/glm-5.2
      api_base: https://api.z.ai/api/anthropic
      api_key: os.environ/ZAI_API_KEY
      extra_body:
        thinking:
          type: "enabled"
        reasoning_effort: "max"