model_list:
  - model_name: claude-3-5-sonnet-latest
    litellm_params:
      model: openrouter/z-ai/glm-5.2
      api_key: os.environ/OPENROUTER_API_KEY
      extra_body:
        reasoning:
          effort: "high"
          exclude: true # Highly recommended for Claude Code

  - model_name: claude-opus-4-8
    litellm_params:
      model: openrouter/z-ai/glm-5.2
      api_key: os.environ/OPENROUTER_API_KEY
      extra_body:
        reasoning:
          effort: "xhigh"
          exclude: true # Highly recommended for Claude Code